//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarketSimulator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockMarketSimulator.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid email (ex. john@domain.com).
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is invalid. It must be minimum 8 characters length, containing an upper letter and a number..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us!.
        /// </summary>
        internal static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Trade!.
        /// </summary>
        internal static string LetsTrade {
            get {
                return ResourceManager.GetString("LetsTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert
        {
            get
            {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to QuantityCheckMessage.
        /// </summary>
        internal static string QuantityCheckMessage
        {
            get
            {
                return ResourceManager.GetString("QuantityCheckMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        internal static string Owned
        {
            get
            {
                return ResourceManager.GetString("Owned", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Sign
        {
            get
            {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to BudgetCheckMessage.
        /// </summary>
        internal static string BudgetCheckMessage
        {
            get
            {
                return ResourceManager.GetString("BudgetCheckMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to SellCheckMessage.
        /// </summary>
        internal static string SellCheckMessage
        {
            get
            {
                return ResourceManager.GetString("SellCheckMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Passwords don't match!.
        /// </summary>
        internal static string InvalidConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Please insert a name!.
        /// </summary>
        internal static string InvalidName
        {
            get
            {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
    }
}
